# -*- coding: utf-8 -*-
"""20210923

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpmQRV0qKovtp78SHieu3RkrTgUEXjJF
"""

import folium

loc = folium.Map(location= [37.601749, 127.109971], zoom_start =30 )
loc

loc = folium.Map(location=[37.546455, 126.911326], zoom_start = 17)

folium.Marker([37.54896329011445, 126.91327310818717],
              popup = '합정역',
              icon = folium.Icon(color = 'purple', icon='info-sign')
            ).add_to(loc)
folium.Marker([37.54716846594737, 126.91581584230569],
              popup = '성산중학교',
              icon = folium.Icon(color = 'purple', icon = 'info-sign')
              ).add_to(loc)
folium.Marker([37.546743145833545, 126.91280103941354],
              popup = '100주년 기념교회',
              icon = folium.Icon(color = 'purple', icon = 'info-sign')
              ).add_to(loc)

loc.save("hapjung.html")

loc

loc = folium.Map(location=[37.58272388553312, 127.0295852260021], zoom_start = 13)

folium.Marker([37.59170884492381, 127.02882385213148],
              popup = '베나레스',
              icon = folium.Icon(color = 'purple', icon='info-sign')
            ).add_to(loc)
folium.Marker([37.582758424152026, 127.04532446741318],
              popup = '로운샤브샤브',
              icon = folium.Icon(color = 'purple', icon = 'info-sign')
              ).add_to(loc)
folium.Marker([37.58171370911498, 126.9836266570595],
              popup = '르브와',
              icon = folium.Icon(color = 'purple', icon = 'info-sign')
              ).add_to(loc)

folium.Marker([37.580730448908234, 127.00278158155156],
              popup = '마로니에공원',
              icon = folium.Icon(color = 'green', icon = 'info-sign')
              ).add_to(loc)  

folium.Marker([37.572678378942335, 126.97565101250872],
              popup = '세종문화회관',
              icon = folium.Icon(color = 'green', icon = 'info-sign')
              ).add_to(loc)  

folium.Marker([37.54451538012267, 127.03744239689279],
              popup = '서울숲',
              icon = folium.Icon(color = 'green', icon = 'info-sign')
              ).add_to(loc)  

loc.save("my_hot_place_list.html")

loc

